/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/common/Banner.vue')['default']
    CoverPlay: typeof import('./src/components/common/CoverPlay.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/layout/footer/Footer.vue')['default']
    Header: typeof import('./src/components/layout/header/Header.vue')['default']
    IconPark: typeof import('./src/components/common/IconPark.vue')['default']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    MenuList: typeof import('./src/components/layout/menu/MenuList.vue')['default']
    MoreText: typeof import('./src/components/common/MoreText.vue')['default']
    PlayerAction: typeof import('./src/components/layout/footer/PlayerAction.vue')['default']
    PlayerController: typeof import('./src/components/layout/footer/PlayerController.vue')['default']
    PlayerSlider: typeof import('./src/components/layout/footer/PlayerSlider.vue')['default']
    PlayerSong: typeof import('./src/components/layout/footer/PlayerSong.vue')['default']
    PlayerVolumeSlider: typeof import('./src/components/layout/footer/PlayerVolumeSlider.vue')['default']
    PlayList: typeof import('./src/components/layout/playList/PlayList.vue')['default']
    PlayListSongItem: typeof import('./src/components/layout/playList/PlayListSongItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPop: typeof import('./src/components/layout/header/SearchPop.vue')['default']
    SearchSuggest: typeof import('./src/components/layout/header/SearchSuggest.vue')['default']
    SongListItem: typeof import('./src/components/common/SongListItem.vue')['default']
    Title: typeof import('./src/components/common/Title.vue')['default']
    UserInfo: typeof import('./src/components/layout/header/UserInfo.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const Banner: typeof import('./src/components/common/Banner.vue')['default']
  const CoverPlay: typeof import('./src/components/common/CoverPlay.vue')['default']
  const ElAffix: typeof import('element-plus/es')['ElAffix']
  const ElAlert: typeof import('element-plus/es')['ElAlert']
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElBadge: typeof import('element-plus/es')['ElBadge']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElSlider: typeof import('element-plus/es')['ElSlider']
  const ElSpace: typeof import('element-plus/es')['ElSpace']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
  const Footer: typeof import('./src/components/layout/footer/Footer.vue')['default']
  const Header: typeof import('./src/components/layout/header/Header.vue')['default']
  const IconPark: typeof import('./src/components/common/IconPark.vue')['default']
  const Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
  const MenuList: typeof import('./src/components/layout/menu/MenuList.vue')['default']
  const MoreText: typeof import('./src/components/common/MoreText.vue')['default']
  const PlayerAction: typeof import('./src/components/layout/footer/PlayerAction.vue')['default']
  const PlayerController: typeof import('./src/components/layout/footer/PlayerController.vue')['default']
  const PlayerSlider: typeof import('./src/components/layout/footer/PlayerSlider.vue')['default']
  const PlayerSong: typeof import('./src/components/layout/footer/PlayerSong.vue')['default']
  const PlayerVolumeSlider: typeof import('./src/components/layout/footer/PlayerVolumeSlider.vue')['default']
  const PlayList: typeof import('./src/components/layout/playList/PlayList.vue')['default']
  const PlayListSongItem: typeof import('./src/components/layout/playList/PlayListSongItem.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchPop: typeof import('./src/components/layout/header/SearchPop.vue')['default']
  const SearchSuggest: typeof import('./src/components/layout/header/SearchSuggest.vue')['default']
  const SongListItem: typeof import('./src/components/common/SongListItem.vue')['default']
  const Title: typeof import('./src/components/common/Title.vue')['default']
  const UserInfo: typeof import('./src/components/layout/header/UserInfo.vue')['default']
}